### ISSUE TITLE
Prefered privileges

### ISSUE THREAD

**Issue by EllenFawkes** [EllenFawkes/PurrplingBot#132]
For bot-as-service usability is needed prefered privileges defined by admin in config file or storage.

Scenario:
- User handle a command
- ACL looks for prefered privilege.
  - User has preferred privilege DENIED => gone, can't do it
  - User has preferred privilege ALLOWED => okay, do it!
  - User has preferred privilege NONE => continue authorization process
- ACL looks for permisions 
 - Allowed? Do it!
 - Not allowed? Don't it!

Function for resolve preferred privileges returns one of states:

- ALLOWED
- DENIED
- NONE

Special privileges can be specified in configuration file:

```yaml
privileges:
  cmd.alias:
    - role:7895462133648
    - !user:4987654654894
  cmd.ping:
    - @everyone # allow for all
  cmd.armageddon:
    - !@everyone # deny for all
```

Privilege types:

- `user:<userID>` - Restrict permission for specified user
- `role:<roleID>` - Restrict for permission for specified role
- `@everyone` - Restrict permission for everyone
- `@guildOwner` - Restrict permission for guild owner
- `@botAdmin` - Restrict permission for bot administrator

If privilege definition starts with `!` then permission is DENIED. If resource not specified or user check not match any privilege type, then permission is NONE.
